export default {
    ar: {
        name: "اسم",
        phone: "رقم التليفون",
        order: "طلب",
        old_price: "السعر القديم",
        new_price: "السعر الجديد",
        discount: "الخصم",
        discount_price: "سعر الخصم",
        discount_end: "الخصم ينتهي في",
        hours: "ساعات",
        minutes: "دقائق",
        seconds: "ثواني",
        profitable: "مربح!",
        pay_after_receive: "تدفع للطلب فقط بعد استلامه",
    },
    az: {
        name: "Ad",
        phone: "Telefon nömrəsi",
        order: "Sifariş",
        old_price: "Köhnə qiymət",
        new_price: "Yeni qiymət",
        discount: "Endirim",
        discount_price: "Endirimli qiymət",
        discount_end: "Endirim bitir",
        hours: "Saatlar",
        minutes: "Dəqiqələr",
        seconds: "Saniyələr",
        profitable: "Mənfəətli!",
        pay_after_receive: "Sifarişi ancaq qəbul etdikdən sonra ödəyirsiniz",
    },
    bg: {
        name: "Име",
        phone: "Телефонен номер",
        order: "Поръчка",
        old_price: "Стара цена",
        new_price: "Нова цена",
        discount: "Отстъпка",
        discount_price: "Цена с отстъпка",
        discount_end: "Отстъпката свършва в",
        hours: "Часове",
        minutes: "Минути",
        seconds: "Секунди",
        profitable: "Изгодно!",
        pay_after_receive: "Заплащате поръчката само след получаване.",
    },
    bs: {
        name: "Ime",
        phone: "Broj telefona",
        order: "Narudžba",
        old_price: "Stara cijena",
        new_price: "Nova cijena",
        discount: "Popust",
        discount_price: "Cijena s popustom",
        discount_end: "Popust završava za",
        hours: "Sati",
        minutes: "Minute",
        seconds: "Sekunde",
        profitable: "Isplativo!",
        pay_after_receive: "Plaćate narudžbu samo nakon što je primite",
    },
    cs: {
        name: "Jméno",
        phone: "Telefonní číslo",
        order: "Objednávka",
        old_price: "Stará cena",
        new_price: "Nová cena",
        discount: "Sleva",
        discount_price: "Cena se slevou",
        discount_end: "Sleva končí za",
        hours: "Hodiny",
        minutes: "Minuty",
        seconds: "Sekundy",
        profitable: "Výhodné!",
        pay_after_receive: "Za objednávku platíte až po jejím přijetí",
    },
    da: {
        name: "Navn",
        phone: "Telefonnummer",
        order: "Ordre",
        old_price: "Gammel pris",
        new_price: "Ny pris",
        discount: "Rabat",
        discount_price: "Rabatpris",
        discount_end: "Rabat slutter om",
        hours: "Timer",
        minutes: "Minutter",
        seconds: "Sekunder",
        profitable: "Profitabelt!",
        pay_after_receive: "Du betaler for ordren kun efter du har modtaget den",
    },
    de: {
        name: "Name",
        phone: "Telefonnummer",
        order: "Bestellung",
        old_price: "Alter Preis",
        new_price: "Neuer Preis",
        discount: "Rabatt",
        discount_price: "Rabattpreis",
        discount_end: "Rabatt endet in",
        hours: "Stunden",
        minutes: "Minuten",
        seconds: "Sekunden",
        profitable: "Profitabel!",
        pay_after_receive: "Sie zahlen für die Bestellung erst nach Erhalt",
    },
    el: {
        name: "Όνομα",
        phone: "Αριθμός τηλεφώνου",
        order: "Παραγγελία",
        old_price: "Παλιά τιμή",
        new_price: "Νέα τιμή",
        discount: "Έκπτωση",
        discount_price: "Τιμή έκπτωσης",
        discount_end: "Η έκπτωση τελειώνει σε",
        hours: "Ώρες",
        minutes: "Λεπτά",
        seconds: "Δευτερόλεπτα",
        profitable: "Κερδοφόρο!",
        pay_after_receive: "Πληρώνετε για την παραγγελία μόνο μετά την παραλαβή της",
    },
    en: {
        name: "Name",
        phone: "Phone number",
        order: "Order",
        old_price: "Old price",
        new_price: "New price",
        discount: "Discount",
        discount_price: "Discount price",
        discount_end: "Discount ends in",
        hours: "Hours",
        minutes: "Minutes",
        seconds: "Seconds",
        profitable: "Profitable!",
        pay_after_receive: "You pay for the order only after receiving it",
    },
    et: {
        name: "Nimi",
        phone: "Telefoninumber",
        order: "Tellimus",
        old_price: "Vana hind",
        new_price: "Uus hind",
        discount: "Allahindlus",
        discount_price: "Allahinnatud hind",
        discount_end: "Allahindlus lõpeb",
        hours: "Tunnid",
        minutes: "Minutid",
        seconds: "Sekundid",
        profitable: "Kasumlik!",
        pay_after_receive: "Te maksate tellimuse eest alles pärast selle kättesaamist",
    },
    es: {
        name: "Nombre",
        phone: "Número de teléfono",
        order: "Pedir",
        old_price: "Precio antiguo",
        new_price: "Precio nuevo",
        discount: "Descuento",
        discount_price: "Precio de descuento",
        discount_end: "El descuento termina en",
        hours: "Horas",
        minutes: "Minutos",
        seconds: "Segundos",
        profitable: "Rentable!",
        pay_after_receive: "Usted paga por el pedido solo después de recibirlo",
    },
    fl: {
        name: "Pangalan",
        phone: "Numero ng telepono",
        order: "Order",
        old_price: "Dating presyo",
        new_price: "Bagong presyo",
        discount: "Discount",
        discount_price: "Presyong may diskuwento",
        discount_end: "Ang diskuwento ay magtatapos sa loob ng",
        hours: "Oras",
        minutes: "Minuto",
        seconds: "Segundo",
        profitable: "Makabuluhan!",
        pay_after_receive: "Magbabayad ka lamang para sa order matapos mo itong matanggap",
    },
    fr: {
        name: "Nom",
        phone: "Numéro de téléphone",
        order: "Ordre",
        old_price: "Ancien prix",
        new_price: "Nouveau prix",
        discount: "Réduction",
        discount_price: "Prix réduit",
        discount_end: "La réduction se termine dans",
        hours: "Heures",
        minutes: "Minutes",
        seconds: "Secondes",
        profitable: "Rentable!",
        pay_after_receive: "Vous payez la commande seulement après l'avoir reçue",
    },
    ka: {
        name: "სახელი",
        phone: "ტელეფონის ნომერი",
        order: "შეკვეთა",
        old_price: "ძველი ფასი",
        new_price: "ახალი ფასი",
        discount: "ფასდაკლება",
        discount_price: "ფასდაკლების ფასი",
        discount_end: "ფასდაკლება სრულდება",
        hours: "საათები",
        minutes: "წუთები",
        seconds: "წამები",
        profitable: "მოგებითი!",
        pay_after_receive: "შეკვეთას მხოლოდ მიღების შემდეგ გადაიხდით",
    },
    kk: {
        name: "Аты",
        phone: "Телефон нөмірі",
        order: "Тапсырыс",
        old_price: "Ескі баға",
        new_price: "Жаңа баға",
        discount: "Жеңілдік",
        discount_price: "Жеңілдік баға",
        discount_end: "Жеңілдік бітуіне дейін",
        hours: "Сағаттар",
        minutes: "Минуттар",
        seconds: "Секундтар",
        profitable: "Керісімді!",
        pay_after_receive: "Тапсырымды алғаннан кейін тек төлейсіз",
    },
    ky: {
        name: "Аты",
        phone: "Телефон номери",
        order: "Буйрутма",
        old_price: "Эски баа",
        new_price: "Жаңы баа",
        discount: "Арзаанатуу",
        discount_price: "Арзаанатуулуу баа",
        discount_end: "Арзаанатуу болуп айтканда",
        hours: "Саат",
        minutes: "Мүнөт",
        seconds: "Секунд",
        profitable: "Пайдалуу!",
        pay_after_receive: "Тапшыруу алганга чейин гана төлөсүз",
    },
    id: {
        name: "Nama",
        phone: "Nomor telepon",
        order: "Pesan",
        old_price: "Harga lama",
        new_price: "Harga baru",
        discount: "Diskon",
        discount_price: "Harga diskon",
        discount_end: "Diskon berakhir dalam",
        hours: "Jam",
        minutes: "Menit",
        seconds: "Detik",
        profitable: "Menguntungkan!",
        pay_after_receive: "Anda membayar pesanan hanya setelah menerima",
    },
    it: {
        name: "Nome",
        phone: "Numero di telefono",
        order: "Ordine",
        old_price: "Vecchio prezzo",
        new_price: "Nuovo prezzo",
        discount: "Sconto",
        discount_price: "Prezzo scontato",
        discount_end: "Lo sconto termina in",
        hours: "Ore",
        minutes: "Minuti",
        seconds: "Secondi",
        profitable: "Redditizio!",
        pay_after_receive: "Paghi l'ordine solo dopo averlo ricevuto",
    },
    ga: {
        name: "Ainm",
        phone: "Uimhir gutháin",
        order: "Ordú",
        old_price: "Seanphraghas",
        new_price: "Praghas nua",
        discount: "Lascaine",
        discount_price: "Praghas lascaine",
        discount_end: "Críochnaíonn an lascaine i",
        hours: "Uaireanta",
        minutes: "Nóiméid",
        seconds: "Soicind",
        profitable: "Brabúseach!",
        pay_after_receive: "Íocann tú as an ordú tar éis é a fháil",
    },
    he: {
        name: "שם",
        phone: "מספר טלפון",
        order: "הזמנה",
        old_price: "מחיר ישן",
        new_price: "מחיר חדש",
        discount: "הנחה",
        discount_price: "מחיר לאחר הנחה",
        discount_end: "ההנחה מסתיימת בעוד",
        hours: "שעות",
        minutes: "דקות",
        seconds: "שניות",
        profitable: "משתלם!",
        pay_after_receive: "אתה משלם עבור ההזמנה רק לאחר קבלתה",
    },
    hi: {
        name: "नाम",
        phone: "फ़ोन नंबर",
        order: "आदेश",
        old_price: "पुरानी कीमत",
        new_price: "नई कीमत",
        discount: "छूट",
        discount_price: "छूट कीमत",
        discount_end: "छूट समाप्त होती है",
        hours: "घंटे",
        minutes: "मिनट",
        seconds: "सेकंड",
        profitable: "लाभदायक!",
        pay_after_receive: "आपको ऑर्डर प्राप्त होने के बाद ही भुगतान करना होगा",
    },
    hu: {
        name: "Név",
        phone: "Telefonszám",
        order: "Rendelés",
        old_price: "Régi ár",
        new_price: "Új ár",
        discount: "Kedvezmény",
        discount_price: "Kedvezményes ár",
        discount_end: "A kedvezmény vége",
        hours: "Órák",
        minutes: "Percek",
        seconds: "Másodpercek",
        profitable: "Nyereséges!",
        pay_after_receive: "Csak a rendelés átvétele után fizet",
    },
    lt: {
        name: "Vardas",
        phone: "Telefono numeris",
        order: "Užsakymas",
        old_price: "Sena kaina",
        new_price: "Nauja kaina",
        discount: "Nuolaida",
        discount_price: "Kaina su nuolaida",
        discount_end: "Nuolaida baigiasi",
        hours: "Valandos",
        minutes: "Minutės",
        seconds: "Sekundės",
        profitable: "Pelninga!",
        pay_after_receive: "Užsakymą apmokate tik gavę",
    },
    lv: {
        name: "Vārds",
        phone: "Telefona numurs",
        order: "Pasūtījums",
        old_price: "Vecā cena",
        new_price: "Jaunā cena",
        discount: "Atlaide",
        discount_price: "Cena ar atlaidi",
        discount_end: "Atlaide beidzas",
        hours: "Stundas",
        minutes: "Minūtes",
        seconds: "Sekundes",
        profitable: "Izdevīgi!",
        pay_after_receive: "Jūs apmaksājat pasūtījumu tikai pēc tā saņemšanas",
    },
    mk: {
        name: "Име",
        phone: "Телефонски број",
        order: "Нарачка",
        old_price: "Стара цена",
        new_price: "Нова цена",
        discount: "Попуст",
        discount_price: "Цена со попуст",
        discount_end: "Попустот завршува за",
        hours: "Часови",
        minutes: "Минути",
        seconds: "Секунди",
        profitable: "Исплатливо!",
        pay_after_receive: "Плаќате за нарачката само откако ќе ја примите",
    },
    mo: {
        name: "Nume",
        phone: "Număr de telefon",
        order: "Ordin",
        old_price: "Preț vechi",
        new_price: "Preț nou",
        discount: "Reducere",
        discount_price: "Preț cu reducere",
        discount_end: "Reducerea se termină în",
        hours: "Ore",
        minutes: "Minute",
        seconds: "Secunde",
        profitable: "Profitabil!",
        pay_after_receive: "Plătiți pentru comandă doar după ce o primiți",
    },
    ms: {
        name: "Nama",
        phone: "Nombor telefon",
        order: "Pesanan",
        old_price: "Harga lama",
        new_price: "Harga baru",
        discount: "Diskaun",
        discount_price: "Harga diskaun",
        discount_end: "Diskaun berakhir dalam",
        hours: "Jam",
        minutes: "Minit",
        seconds: "Saat",
        profitable: "Menguntungkan!",
        pay_after_receive: "Anda membayar untuk pesanan hanya setelah menerima",
    },
    ne: {
        name: "नाम",
        phone: "फोन नम्बर",
        order: "अर्डर",
        old_price: "पुरानो मूल्य",
        new_price: "नयाँ मूल्य",
        discount: "छुट",
        discount_price: "छुट मूल्य",
        discount_end: "छुट समाप्त हुन्छ",
        hours: "घण्टा",
        minutes: "मिनेट",
        seconds: "सेकेन्ड",
        profitable: "नाफामुलक!",
        pay_after_receive: "तपाईले अर्डर प्राप्त गरेपछि मात्र भुक्तानी गर्नुहुन्छ।",
    },
    nl: {
        name: "Naam",
        phone: "Telefoonnummer",
        order: "Bestelling",
        old_price: "Oude prijs",
        new_price: "Nieuwe prijs",
        discount: "Korting",
        discount_price: "Kortingsprijs",
        discount_end: "Korting eindigt in",
        hours: "Uren",
        minutes: "Minuten",
        seconds: "Seconden",
        profitable: "Winstgevend!",
        pay_after_receive: "U betaalt voor de bestelling alleen na ontvangst ervan",
    },
    pl: {
        name: "Imię",
        phone: "Numer telefonu",
        order: "Zamówienie",
        old_price: "Stara cena",
        new_price: "Nowa cena",
        discount: "Zniżka",
        discount_price: "Cena po zniżce",
        discount_end: "Zniżka kończy się za",
        hours: "Godziny",
        minutes: "Minuty",
        seconds: "Sekundy",
        profitable: "Opłacalne!",
        pay_after_receive: "Płacisz za zamówienie dopiero po jego otrzymaniu",
    },
    pt: {
        name: "Nome",
        phone: "Número de telefone",
        order: "Pedido",
        old_price: "Preço antigo",
        new_price: "Novo preço",
        discount: "Desconto",
        discount_price: "Preço com desconto",
        discount_end: "Desconto termina em",
        hours: "Horas",
        minutes: "Minutos",
        seconds: "Segundos",
        profitable: "Lucrativo!",
        pay_after_receive: "Você paga pelo pedido somente após recebê-lo",
    },
    ro: {
        name: "Nume",
        phone: "Număr de telefon",
        order: "Comandă",
        old_price: "Preț vechi",
        new_price: "Preț nou",
        discount: "Reducere",
        discount_price: "Preț cu reducere",
        discount_end: "Reducerea se termină în",
        hours: "Ore",
        minutes: "Minute",
        seconds: "Secunde",
        profitable: "Profitabil!",
        pay_after_receive: "Plătiți pentru comandă doar după ce o primiți",
    },
    ru: {
        name: "Имя",
        phone: "Номер телефона",
        order: "Заказать",
        old_price: "Старая цена",
        new_price: "Новая цена",
        discount: "Скидка",
        discount_price: "Цена со скидкой",
        discount_end: "Скидка заканчивается через",
        hours: "Часы",
        minutes: "Минуты",
        seconds: "Секунды",
        profitable: "Выгодно!",
        pay_after_receive: "Вы платите за заказ только после его получения",
    },
    sr: {
        name: "Ime",
        phone: "Broj telefona",
        order: "Narudžba",
        old_price: "Стара цена",
        new_price: "Нова цена",
        discount: "Попуст",
        discount_price: "Цена са попустом",
        discount_end: "Попуст завршава за",
        hours: "Сати",
        minutes: "Минути",
        seconds: "Секунде",
        profitable: "Профитабилно!",
        pay_after_receive: "Плаћате наруџбину само након што је примите",
    },
    sk: {
        name: "Meno",
        phone: "Telefónne číslo",
        order: "Objednávka",
        old_price: "Stará cena",
        new_price: "Nová cena",
        discount: "Zľava",
        discount_price: "Cena so zľavou",
        discount_end: "Zľava končí za",
        hours: "Hodiny",
        minutes: "Minúty",
        seconds: "Sekundy",
        profitable: "Výhodné!",
        pay_after_receive: "Za objednávku platíte až po jej prijatí",
    },
    sl: {
        name: "Ime",
        phone: "Telefonska številka",
        order: "Naročilo",
        old_price: "Stara cena",
        new_price: "Nova cena",
        discount: "Popust",
        discount_price: "Cena s popustom",
        discount_end: "Popust se konča čez",
        hours: "Ure",
        minutes: "Minute",
        seconds: "Sekunde",
        profitable: "Donosno!",
        pay_after_receive: "Za naročilo plačate šele po prejemu",
    },
    sv: {
        name: "Namn",
        phone: "Telefonnummer",
        order: "Order",
        old_price: "Gammalt pris",
        new_price: "Nytt pris",
        discount: "Rabatt",
        discount_price: "Rabatterat pris",
        discount_end: "Rabatten slutar om",
        hours: "Timmar",
        minutes: "Minuter",
        seconds: "Sekunder",
        profitable: "Lönsamt!",
        pay_after_receive: "Du betalar för beställningen endast efter att du har mottagit den",
    },
    th: {
        name: "ชื่อ",
        phone: "หมายเลขโทรศัพท์",
        order: "การสั่งซื้อ",
        old_price: "ราคาเดิม",
        new_price: "ราคาใหม่",
        discount: "ส่วนลด",
        discount_price: "ราคาส่วนลด",
        discount_end: "ส่วนลดสิ้นสุดใน",
        hours: "ชั่วโมง",
        minutes: "นาที",
        seconds: "วินาที",
        profitable: "คุ้มค่า!",
        pay_after_receive: "คุณจ่ายสำหรับคำสั่งซื้อเฉพาะหลังจากได้รับ",
    },
    tk: {
        name: "At",
        phone: "Telefon belgisi",
        order: "Sargytmak",
        old_price: "Köne bahasy",
        new_price: "Täze bahasy",
        discount: "Arzanladýar",
        discount_price: "Arzanlatylan bahasy",
        discount_end: "Arzanladýar şu wagtda gutarýar",
        hours: "Sagat",
        minutes: "Minut",
        seconds: "Sekunda",
        profitable: "Peýdaly!",
        pay_after_receive: "Sargyt üçin diňe alanyňyzdan soň töleýärsiňiz.",
    },
    tr: {
        name: "İsim",
        phone: "Telefon numarasi",
        order: "Sipariş",
        old_price: "Eski fiyat",
        new_price: "Yeni fiyat",
        discount: "İndirim",
        discount_price: "İndirimli fiyat",
        discount_end: "İndirim şu sürede sona eriyor",
        hours: "Saat",
        minutes: "Dakika",
        seconds: "Saniye",
        profitable: "Karlı!",
        pay_after_receive: "Siparişi yalnızca aldıktan sonra ödersiniz",
    },
    uz: {
        name: "Ism",
        phone: "Telefon raqami",
        order: "Buyurtma",
        old_price: "Eski narx",
        new_price: "Yangi narx",
        discount: "Chegirma",
        discount_price: "Chegirmali narx",
        discount_end: "Chegirma tugaydi",
        hours: "Soatlar",
        minutes: "Daqiqalar",
        seconds: "Soniya",
        profitable: "Foydali!",
        pay_after_receive: "Buyurtmani faqat qabul qilgandan keyin to'lasiz",
    },
    vi: {
        name: "Tên",
        phone: "Số điện thoại",
        order: "Đặt hàng",
        old_price: "Giá cũ",
        new_price: "Giá mới",
        discount: "Giảm giá",
        discount_price: "Giá giảm giá",
        discount_end: "Giảm giá kết thúc trong",
        hours: "Giờ",
        minutes: "Phút",
        seconds: "Giây",
        profitable: "Có lợi!",
        pay_after_receive: "Bạn chỉ thanh toán cho đơn hàng sau khi nhận được",
    },
};
